### ISSUE TITLE
Learning materials

### ISSUE THREAD

**Issue by SKioresku** [PetWorm/LARVIO#4]
Hi! I'm trying to learn LARVIO implementration, but i have poor knowledge in the field of inertial sensors. Could You tell me what books can help in understanding the work?

**Comment by PetWorm** [comment]
Sorry for the late response.
I personally studied inertial sensors knowledge from Chinese textbook. Well there is an English book named "Strapdown Inertial Navigation Technology" which may serve as a solid material.
For LARVIO, you can refer to our [CJA2020](https://www.sciencedirect.com/science/article/pii/S1000936120301722) and [Sensors2019](https://www.mdpi.com/1424-8220/19/8/1941/htm) papers.
