### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zhizunhu** [PetWorm/LARVIO#5]
邱博士：
    您好！我有一个问题想要请教你，原谅我英文不好，所以选择中文交流。
    我看到你在imu和图像的时间戳处理上，选择以imu时间作为基准，然后通过特征点坐标预测的方式得到当前时刻的视觉观测，我看到很多其他工作是选择以图像时间戳为基准，通过插值的方式得到图像时间对应的imu测量。我想问一下这两种方式有什么优缺点或者异同吗？
祝安

**Comment by PetWorm** [comment]
你好！这个没有什么优缺点之说，习惯不同而已哈。

**Comment by zhizunhu** [comment]
恩，谢谢，我现在还有个问题，我最近在跑VINS系统的时候，不管是VINS-Mono还是LARVIO，发现它们在应对急停场景都有点问题，急停时，系统的位姿都有点漂移，您在这方面有什么想法吗？

**Comment by PetWorm** [comment]
抱歉回复晚了。
这个问题可能需要具体分析。如果是撞击急停，这种没啥好办法，尽量避免；如果是运动急停，可能不一定是急停的问题，而是前面运动很快的时候已经不行了，这种只能提高imu质量了。
另外新的问题咱还是尽量新开个issue哈。
