### ISSUE TITLE
Covariance for dynamic initialization

### ISSUE THREAD

**Issue by Wangxuefeng92** [PetWorm/LARVIO#9]
thanks for your great job on LARVIO！in dynamic initialization，the covariance is not considered for imu_state in LARVIO？ could you have any ideas about the obtian of covariance from your dynamic initialization？

**Comment by PetWorm** [comment]
Good point. 
Theoretically, the inverse of the Hessian from dynamic initialization could somehow approximate the covariance. Might try it in the future.

**Comment by Wangxuefeng92** [comment]
Thanks for your reply! I tried the inverse of the Hessian from your dynamic initialization. but unfortunately, the Hessian is not full-rank. Could you have any idea for this situation?
